#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan  6 12:25:49 2021

@author: RileyBallachay
"""
import threading

def worker():
    """thread worker function"""
    print ('Worker')
    return

threads = []
for i in range(5):
    t = threading.Thread(target=worker)
    threads.append(t)
    t.start()