#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 27 10:34:32 2020

@author: RileyBallachay
"""
import numpy as np
import random
import matplotlib.pyplot as plt

def PRBS(mean,nstep=100):  
        """Returns a pseudo-random binary sequence 
        which ranges between -1 and +1"""
        gbn = np.zeros(nstep)
        loc=0
        currentval = np.random.choice([-1,1])
        dist = [int(round(i,0)) for i in np.random.normal(mean,mean/2,nstep)]
        print(np.mean(dist))
        i=0
        while loc<(nstep-1):
            stride = dist[i]
            if loc+stride>(nstep-1):
                gbn[loc:] = currentval     
            else:
                gbn[loc:loc+stride] = currentval
                currentval = -currentval
            loc = loc+stride
            i+=1
        return gbn

switches = [5,10,15,20,25,30,35]
frequencies = []

for switch in switches:
    avgs = []
    for i in range(1000):
        prbs=PRBS(switch)
        sequences=[]
        temp=1
        lasti = prbs[0]
        for index,i in enumerate(prbs[1:]): 
            if i==lasti:
                temp+=1
            else:
                sequences.append(temp)
                temp=1
            lasti=i
        sequences.append(temp)
        avgs+=sequences
    
    avgs=np.array(avgs)
    mean = np.nanmean(avgs)
    stdev = np.nanstd(avgs)
    frequencies.append(mean)
    print(("Probability Switch: %.2f" % switch))
    print(("Period: %.2f +/- %.2f" % (mean,stdev)))
    plt.figure(dpi=200)
    plt.hist(avgs,bins=10,label=("Probability Switch: %.2f" % switch))
    plt.xlabel("PRBS Period")
    plt.ylabel("Density")
    plt.legend()
    
plt.figure(dpi=200)
plt.plot(switches,frequencies)